risada = input()
risada = risada.replace('b','')
risada = risada.replace('c','')
risada = risada.replace('d','')
risada = risada.replace('f','')
risada = risada.replace('g','')
risada = risada.replace('h','')
risada = risada.replace('j','')
risada = risada.replace('k','')
risada = risada.replace('l','')
risada = risada.replace('m','')
risada = risada.replace('n','')
risada = risada.replace('z','')
risada = risada.replace('p','')
risada = risada.replace('q','')
risada = risada.replace('r','')
risada = risada.replace('s','')
risada = risada.replace('t','')
risada = risada.replace('v','')
risada = risada.replace('w','')
risada = risada.replace('x','')
risada = risada.replace('y','')
risada1 = risada[::-1]
if risada == risada1:
    print("S")
else:
    print("N")
