a = input()
b = input()
c = input()
print("A = " + a + ", " + "B = " + b + ", " + "C = " + c)
print("A = " + b + ", " + "B = " + c + ", " + "C = " + a)
print("A = " + c + ", " + "B = " + a + ", " + "C = " + b)
