#!/bin/python3

import sys

def minimumAbsoluteDifference(n, arr):
    menor = 1000000000
    arr.sort()
    for i in range(len(arr)-1):
        if abs(arr[i]-arr[i+1]) < menor:
            menor = abs(arr[i]-arr[i+1])
    return menor

if __name__ == "__main__":
    n = int(input().strip())
    arr = list(map(int, input().strip().split(' ')))
    result = minimumAbsoluteDifference(n, arr)
    print(result)
